tokens/transition.json
As aligned with @annsch
Preview: https://db-ui.github.io/base/review/feat-added-transition-tokens/css/variables.css (at the end)
=> feat: added first stack of transition tokens

.github/workflows/00-scan-secrets.yml, .github/workflows/99-auto-merge.yml
inspired by https://github.com/dependabot/fetch-metadata/pull/246
=> refactor: not pinning CI/CD dependencies

.github/workflows/default.yml
We'd like to have a checks-done step within our pipeline that we could bind our success checks regarding merges to.
=> feat: add checks-done job

.github/workflows/default.yml
Follow up for https://github.com/db-ui/base/pull/95
=> chore: let's make checks done great again

.github/actions/extract-branch/action.yml, .github/scripts/build-gh-page.sh, .github/workflows/00-scan-secrets.yml
from https://github.com/db-ui/elements/commit/d07fae26170427ed683828bbba146309de425dcb
=> refactor: adapted pipeline script parts

.github/workflows/02-deploy-gh-pages.yml, .github/workflows/default.yml, .github/workflows/pull-request-opened.yml, .github/workflows/pull-request.yml
We need to check for another [GitHub environment variable](https://docs.github.com/en/actions/learn-github-actions/environment-variables).
=> fix(pipeline): steps skipped

scss/color/_color-variants.scss
Welcome to your brothers and sisters
=> feat: add color-variants for components

scss/icon/_icons.helpers.scss
into the CSS Variable fallback section
Resolves https://github.com/db-ui/base/issues/169
=> refactor: moved the defaults / fallbacks

.vscode/extensions.json
Added [VS Code Axe Linter plugin](https://marketplace.visualstudio.com/items?itemName=deque-systems.vscode-axe-linter) as well as [HTML Validate](https://marketplace.visualstudio.com/items?itemName=html-validate.vscode-html-validate) to suggestions list.
Inspired by incredible @d-koppenhagen
=> feat(test): added VS Code plugin suggestion

.github/workflows/default.yml
=> refactor(dependabot): skip deploy step

scripts/color-placeholders-generator.js
=> Feat: color placeholder text only

scss/_init.scss
closes [#232](https://github.com/db-ui/core/issues/232)
=> refactor: move basic style sets from core to base

tokens/asset/font.json
=> refactor: added DB Screen Sans Digital Regular font

tokens/color.json
Resolves https://github.com/db-ui/base/issues/304
=> fix: color hex #304

.husky/pre-commit, .lintstagedrc
Resolves https://github.com/db-ui/base/issues/383
=> refactor: consolidated pre-commit scripts #383

.github/dependabot.yml
Resolve https://github.com/db-ui/base/issues/407
=> feat: introduce grouped version updates for `dependabot`

source/_patterns/icons/_icons.demonstration.scss, source/_patterns/logo/_logo.demonstration.scss, source/css/pattern-scaffolding.css
Resolves https://github.com/db-ui/base/issues/562
=> fix(safari): restored list-style type for VoiceOver screenreader

package-lock.json, package.json
as we've updated `validate-branch-name`
=> refactor: removed obsolete overrite

.github/actions/extract-branch/action.yml
Resolves https://github.com/db-ui/base/issues/503
=> refactor: updated `github-script` action

.github/actions/npm-cache/action.yml
https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#node-version-file
=> refactor: using `.nvmrc` entry

tokens/color/transportation.json
- "call-bus": DB Violett 500
- "ev-bus": #9B1B60
- "walk": DB Cool Gray 700 becomes DB Cool Gray 200
=> refactor: added missing and corrected existing transportation colors

.vscode/extensions.json
https://marketplace.visualstudio.com/items?itemName=Kravets.vscode-publint
=> docs: added publint as a VS Code extension suggestion
